project:
  type: website
  output-dir: docs

website:
  title: "TanyaDoesScience"
  favicon: images/logo.png
  navbar:
    title: "TanyaDoesScience"
    logo: images/logo.png
    background: primary
    left:
      - href: index.qmd
        text: home
      - href: projects.qmd
        text: projects
      - href: draws.qmd
        text: draws
    right: 
      - href: CV/CV.pdf
        text: CV

format:
  html:
    theme: [Journal, mystyles.scss]
    css: styles.css
    toc: false
    code-background: true
    code-fold: true

editor: visual


