project:
  type: website
  output-dir: docs

website:
  title: "TanyaDoesScience"
  favicon: images/icon.png
  navbar:
    title: "TanyaDoesScience"
    logo: images/logo.png
    background: primary
    left:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - href: projects.qmd
        text: projects
      - href: publications.qmd
        text: publications
      - href: draws.qmd
        text: draws
      - href: posts.qmd
        text: blog
      - href: resources.qmd
        text: resources
    right: 
      - href: CV/CV.pdf
        text: CV

format:
  html:
    theme: [Journal, mystyles.scss]
    css: styles.css
    toc: false
    code-background: true
    code-fold: true

editor: visual


