---
title: "Coming to Terms With Being a Theoretical Ecologist"
description: |
  Having done some soul searching while working on PhD applications I've come to the conclusion that just maybe I'm not the ecologist that I thought I was.
preview: pattern_box.jpg
author:
  - name: Tanya Strydom
    url: {}
#date: '`r format(Sys.time(), "%Y-%m-%d")`'
categories:
  - "musings"
output:
  distill::distill_article:
    css: 'academicons/css/academicons.min.css'
    self_contained: false
---

<div style="text-align: justify">

While trawling through the interweb looking at advertised PhD positions (as well as stalking some of my favourite researchers) I started to notice a bit of a trend - the topics that I found interesting weren't always linked to a strong field component but rather had fancy statistical and mathematical terms somewhere in the project description (process based modelling and machine learning anyone??). I love being outside, absolutely adore it actually, and always thought the appeal of ecology was the chance to go out to wild and exotic places and do some cool data collecting along the way. But the more I think about the more I think that was just the sun-loving, adrenaline junkie in me...

My analytical brain (I blame having two engineers as parents for this) on the other hand *loves* the data analysis and processing side of things - more specifically playing with and (hopefully) being able to draw meaningful conclusions from the data. I get super excited (and geek out extensively) about all of the cool things and stories I can learn from the data that we've collected. Only to be (mildly) upset when I discover that we don't *really* have enough or all of the data needed to apply the really cool or complex approaches that I would like to take and then being relegated to the more 'vanilla' statistical analyses. But if I think back on it long enough I think it goes back even further than that.

I fondly remember one day in first year over a cup of tea a friend and I were joking about developing a 'master' formula that we could use for all of our calculations for the upcoming physics exam (I mean realistically they're all interconnected but in our defence it was first yet and we were exhausted/delirious). Fast forward to my more recent musings I found myself in a philosophy course where I often brought up how we as ecologists really don't seem to have any concrete laws (except maybe the species area relationship) or that they at least require a fair bit of hand waving and that we don't seem to be actively moving towards that (data synthesis) direction either (*Although I do think that is changing*). Clearly that is what I crave though - developing and working with a model/formula/program that I can apply to my specific research query.

Another tell-tale sign should have been how quickly I adopted the use of functional traits in my data collecting/consideration protocol. I love the concept, not only can we use them to quantify certain ecosystem processes, but we also create an abstraction of the individual - everyone is reduced to their trait value(s) and treated as such. So not only are we able to take data from individuals (and communities) and scale this up to infer various ecosystem processes we also have a sense of generality by using traits. All species (at least within some taxonomic group) share the same traits they are just expressed differently - all plants (if we stick with vascular species) have leaves and as such we can 'reduce' them all to the traits of their leaves e.g. area/mass/water content. This means that we could use these traits in our analyses and would be more likely to make generalisations of our conclusions by saying if an individual has $x$ traits we expect it to respond in such a manner to changes in temperature. Now isn't that an elegant approach!

Some other warning signs probably include the fact that I am very happy when I have R studio open in one window and Stack Overflow in another and have spent the last hour trying to work out why the code that was working has now decided to no longer co-operate, as well as having decided that I ~~needed~~ wanted to take a course in Bayesian Analyses (despite it being a bit of an admin headache) because it "looks really cool". Admittedly this was also when I found out about hierarchical modelling and let me tell you it was love at first sight! Well until I found out that there are even more things you can do by building on that concept.

I guess I have to face the music and accept that I probably love sitting in front of my computer thinking about species in abstract terms and numbers more than being out in the field doing the data collecting - and I _think_ I'm okay with that. 

Although I think it is important to note (as well as open the discussion) that this doesn't make 'other' disciplines of ecology any less important or valid but rather highlights that (much like ecological systems) there is a degree of interdependence and that if the various 'factions' (I feel like I need to work on a better term but sub-discipline just doesn't work for me either) work together we can do even better science and work together to creating more unifying theories and laws ^[maybe another flashing light of my inclination towards wanting to synthesise data is that I abhor the fact that institutions seem to love keeping e.g. the botany and zoology departments as separate entities yet the two fields are so intricately connected...]. This of course can't happen if we work in isolation and further highlights the need for not only data sharing (and open and FAIR science in general) but also inviting researchers from various ecological backgrounds into our research circles and projects so as to maximise our potential to produce results that can then be implemented by various other stakeholders. Gone should be the days of trying to one-up each other and rather we should bring together our various interests, skills and specialisations so as to tackle to ever growing list of problems facing the natural world we all love so much.

Cheers,

Tanya ^[a self diagnosed theoretical ecologist]


</div>
